### PR TITLE
Eyewitness report

### PR DESCRIPTION
**Pull request by Sekinat95**
## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tos4christ** [comment]
@Sekinat95 you need to check the details of the errors codacy is highlighting so that your PR can me merge-able

**Review by Dirkmal — CHANGES_REQUESTED** [review]
Kindly implement changes suggested by Codacy.

**Comment by Dirkmal** [comment]
> Kindly implement changes suggested by Codacy.

Do check the details of the failed checks highlighted by codacy.

**Comment by tos4christ** [comment]
change your parseInt function to parseInt(number, 10) . the number here represents the value your are trying to parse

**Review by tos4christ — COMMENTED** [review]
your parseInt function must have the base e.g parseInt(code.number , 10)

**Comment by tos4christ** [comment]
please change this const mongoose = require('../../common/database/mongoose.db').mongoose;
to 
const { mongoose } = require('../../common/database/mongoose.db');

**Comment by tos4christ** [comment]
const { Schema } = mongoose;

**Review by Dirkmal — APPROVED** [review]

**Review by tos4christ — APPROVED** [review]
Please conform your folder structure to the standard agreed

**Review by bbmattieu9 — COMMENTED** [review]
Good enough.

**Review by bbmattieu9 — APPROVED** [review]
Good enough

**Review by olabiranj — APPROVED** [review]

**Pull request closed without merging**
